name: runtime CMake version
on: [push, pull_request]
jobs:
  minimum-runtime-cmake-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmake_build: [3.16]
        cmake_build_sub_version: [9]
        cmake_runtime: [3.12]
        cmake_runtime_sub_version: [0]
    env:
      CC: gcc-10
      CXX: g++-10
      build_dir: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check dependencies
        run: |
          cmake --version
          sudo apt-get update
          sudo apt-get install -y curl wget git ninja-build g++-10 libboost-all-dev libssl-dev

      - name: Install CMake build minimum version
        run: |
          wget https://cmake.org/files/v${{matrix.cmake_build}}/cmake-${{matrix.cmake_build}}.${{matrix.cmake_build_sub_version}}-Linux-x86_64.sh
          sudo mv cmake-${{matrix.cmake_build}}.${{matrix.cmake_build_sub_version}}-Linux-x86_64.sh /opt
          cd /opt
          sudo chmod +x cmake-${{matrix.cmake_build}}.${{matrix.cmake_build_sub_version}}-Linux-x86_64.sh
          sudo bash ./cmake-${{matrix.cmake_build}}.${{matrix.cmake_build_sub_version}}-Linux-x86_64.sh --skip-license
          sudo cp /opt/bin/{cmake,ccmake,cmake-gui,cpack,ctest} /usr/local/bin
          sudo cp -r /opt/share/{aclocal,applications,cmake-${{matrix.cmake_build}},icons,mime} /usr/local/share
          sudo cp -r /opt/man/{man1,man7} /usr/local/man
          sudo cp -r  /opt/doc/cmake /usr/local/doc
          cmake --version

      - name: CMake configuration
        run: |
          cd /home/runner/work/libSMCE/libSMCE
          export BOOST_ROOT="${pwd}/boost_root"
          mkdir ${build_dir}
          cmake -G Ninja \
            -DSMCE_BUILD_SHARED=On \
            -DSMCE_BUILD_STATIC=On \
            -DSMCE_CXXRT_LINKING=SHARED \
            -DSMCE_BOOST_LINKING=SHARED \
            -DSMCE_ARDRIVO_MQTT=On \
            -DSMCE_MOSQUITTO_LINKING=SHARED \
            -DSMCE_ARDRIVO_OV767X=On \
            -S ./ -B ${build_dir}

      - name: CMake build
        run: |
          cmake --build ${build_dir}

      - name: Run libSMCE&SMCE_Tests target
        run: |
          cmake --build ${build_dir} --target SMCE_Tests
      
      - name: Reintsall CMake
        run: |
          wget https://cmake.org/files/v${{matrix.cmake_runtime}}/cmake-${{matrix.cmake_runtime}}.${{matrix.cmake_runtime_sub_version}}-Linux-x86_64.sh
          sudo mv cmake-${{matrix.cmake_runtime}}.${{matrix.cmake_runtime_sub_version}}-Linux-x86_64.sh /opt
          cd /opt
          sudo chmod +x cmake-${{matrix.cmake_runtime}}.${{matrix.cmake_runtime_sub_version}}-Linux-x86_64.sh
          sudo bash ./cmake-${{matrix.cmake_runtime}}.${{matrix.cmake_runtime_sub_version}}-Linux-x86_64.sh --skip-license
          sudo cp /opt/bin/{cmake,ccmake,cmake-gui,cpack,ctest} /usr/local/bin
          sudo cp -r /opt/share/{aclocal,applications,cmake-${{matrix.cmake_runtime}},icons,mime} /usr/local/share
          sudo cp -r /opt/man/{man1,man7} /usr/local/man
          sudo cp -r  /opt/doc/cmake /usr/local/doc
          cmake --version

      - name: Runtime tests
        run: |
          pwd
          cd ${build_dir}/test
          ctest
