name: runtime CMake version
on: [push, pull_request]
jobs:
  minimum-runtime-cmake-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmake_build: [3.16]
        cmake_runtime: [3.12]

    env:
      cmake_build: ${{matrix.cmake_build}}
      cmake_runtime: ${{matrix.cmake_runtime}}
      build_dir: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check dependencies
        run: |
          cmake --version
          sudo apt-get update
          sudo apt-get install -y curl wget git ninja-build g++ libboost-all-dev libssl-dev

      - name: Install CMake build minimum version
        run: |
          cd /usr/local/bin
          rm cmake ccmake cmake-gui cpack ctest
          wget https://cmake.org/files/v${{matrix.cmake_build}}/cmake-${{matrix.cmake_build}}.0-Linux-x86_64.sh
          sudo mv cmake-${{matrix.cmake_build}}.0-Linux-x86_64.sh /opt
          cd /opt
          sudo chmod +x cmake-${{matrix.cmake_build}}.0-Linux-x86_64.sh
          sudo bash ./cmake-${{matrix.cmake_build}}.0-Linux-x86_64.sh --skip-license
          sudo cp /opt/bin/{cmake,ccmake,cmake-gui,cpack,ctest} /usr/local/bin
          ls
          sudo cp -r /opt/share/{aclocal,applications,cmake-3.16,icons,mime} /usr/local/share
          sudo cp -r /opt/man/{man1,man7} /usr/local/man
          sudo cp -r  /opt/doc/cmake /usr/local/doc
          cmake --version
          pwd
          ls

      - name: CMake configuration
        run: |
          cd /home/runner/work/libSMCE/libSMCE
          export BOOST_ROOT="${pwd}/boost_root"
          mkdir ${build_dir}
          cmake -S ./ -B ${build_dir}

      - name: CMake build
        run: |
          cmake --build ${build_dir}

      - name: Run libSMCE&SMCE_Tests target
        run: |
          cmake --build ${build_dir} --target SMCE_Tests
      
      - name: Reintsall CMake
        run: |
          pwd
          sudo rm -r /opt/
          wget https://cmake.org/files/v${{matrix.cmake_runtime}}/cmake-${{matrix.cmake_runtime}}.0-Linux-x86_64.sh
          sudo mv cmake-${{matrix.cmake_runtime}}.0-Linux-x86_64.sh /opt
          cd /opt
          sudo chmod +x cmake-${{matrix.cmake_runtime}}.0-Linux-x86_64.sh
          sudo bash ./cmake-${{matrix.cmake_runtime}}.0-Linux-x86_64.sh
          sudo ln -s /opt/cmake-${{matrix.cmake_runtime}}.0-Linux-x86_64.sh/bin/* /usr/local/bin
          cmake --version
          pwd

      - name: Runtime tests
        run: |
          pwd
          cd ${build_dir}/test
          ctest
