name: runtime cmake version check
on: [push, pull_request]
jobs:
    minimum-version-check:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                cmake_newer: [3.16]
                cmake_older: [3.12]
                        
                compiler:
                    - cc: gcc-10
                      cxx: g++-10
                    - cc: clang-10
                      cxx: clang++-10          
        env:
            cmake_newer: ${{ matrix.cmake_newer }} 
            cmake_older: ${{ matrix.cmake_older }}
            CC: ${{ matrix.compiler.cc }}
            CXX: ${{ matrix.compiler.cxx }} 
            build_dir: build
           
        steps:  
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Check dependencies
              run: |
                  sudo apt-get update 
                  sudo apt-get install -y curl wget git ninja-build g++ libboost-all-dev libssl-dev
                  
            - name: Install different versions of cmake
              run: |
                  wget http://www.cmake.org/files/v${{ matrix.cmake_newer }}/cmake-${{ matrix.cmake_newer }}.0-Linux-x86_64.tar.gz
                  sudo tar -xzvf cmake-${{ matrix.cmake_newer }}.0-Linux-x86_64.tar.gz -C /usr/local/bin
                  cd /usr/local/bin/cmake-${{ matrix.cmake_newer }}.0-Linux-x86_64/
                  echo 'export PATH=$PATH:$(pwd)/bin'>> ~/.bashrc
                  source ~/.bashrc
                  cmake --version
              
            - name: CMake configure
              run: |
                  export BOOST_ROOT="$(pwd)/boost_root"
                  mkdir build
                  cmake -S ./ -B ./build
                  
            - name: CMake build
              run: |
                  cmake --build ./build
              
            - name: Run libSMCE & SMCE_Tests
              run: |
                 cmake --build ./build --target SMCE_Tests
             
            - name: Unistall cmake
              run: |
                cd /usr/local/bin/
                sudo rm -r cmake-${{ matrix.cmake_newer }}.0-Linux-x86_64
                
            - name: Reinstall cmake
              run: |
                  wget http://www.cmake.org/files/v${{ matrix.cmake_older }}/cmake-${{ matrix.cmake_older }}.0-Linux-x86_64.tar.gz
                  sudo tar -xzvf cmake-${{ matrix.cmake_older }}.0-Linux-x86_64.tar.gz -C /usr/local/bin
                  cd /usr/local/bin/cmake-${{ matrix.cmake_older }}.0-Linux-x86_64/
                  echo 'export PATH=$PATH:$(pwd)/bin'>> ~/.bashrc
                  source ~/.bashrc
                  cmake --version
               
            - name: Run tests
              run: |
                  cd /home/runner/work/libSMCE/libSMCE/build/test 
                  ctest
