name: runtime CMake version
on: [push, pull_request]
jobs:
  minimum-runtime-cmake-version:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cmake_build: [ 3 ]
        cmake_build_sub_release: [ 16, 17, 18, 19 ]
        cmake_build_sub_version: [ 5 ]
        cmake_runtime: [ 3 ]
        cmake_runtime_sub_release: [ 12, 13, 14, 15, 16, 17, 18, 19 ]
        cmake_runtime_sub_version: [ 4 ]
    env:
      CC: gcc-10
      CXX: g++-10
      current_build_cmake_version_short: ${{matrix.cmake_build}}.${{matrix.cmake_build_sub_release}}
      current_build_cmake_version_complete: ${{matrix.cmake_build}}.${{matrix.cmake_build_sub_release}}.${{matrix.cmake_build_sub_version}}
      current_runtime_cmake_version_short: ${{matrix.cmake_runtime}}.${{matrix.cmake_runtime_sub_release}}
      current_runtime_cmake_version_complete: ${{matrix.cmake_runtime}}.${{matrix.cmake_runtime_sub_release}}.${{matrix.cmake_runtime_sub_version}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check dependencies
        run: |
          cmake --version
          sudo apt-get update
          sudo apt-get install -y curl wget git ninja-build g++-10 libssl-dev libmosquitto-dev

      - name: Install CMake build minimum version
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v${current_build_cmake_version_complete}/cmake-${current_build_cmake_version_complete}-Linux-x86_64.sh
          sudo chmod +x cmake-${current_build_cmake_version_complete}-Linux-x86_64.sh
          sudo bash ./cmake-${current_build_cmake_version_complete}-Linux-x86_64.sh --skip-license --prefix=/usr/local
          cmake --version

      - name: CMake configuration
        run: |
          cd /home/runner/work/libSMCE/libSMCE
          mkdir build
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DSMCE_CXXRT_LINKING=STATIC \
            -DSMCE_BOOST_LINKING=SOURCE\
            -DSMCE_OPENSSL_LINKING=STATIC \
            -S ./ -B ./build
          ls build/test
            
      - name: CMake build
        run: |
          cmake --build build

      - name: Run libSMCE&SMCE_Tests target
        run: |
          cmake --build build --target SMCE_Tests
      
      - name: Reintsall CMake runtime minimum version
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v${current_runtime_cmake_version_complete}/cmake-${current_runtime_cmake_version_complete}-Linux-x86_64.sh
          sudo chmod +x cmake-${current_runtime_cmake_version_complete}-Linux-x86_64.sh
          sudo bash ./cmake-${current_runtime_cmake_version_complete}-Linux-x86_64.sh --skip-license --prefix=/usr/local
          cmake --version

      - name: Runtime tests
        run: |
          cd /home/runner/work/libSMCE/libSMCE/build/test
          ctest --output-on-error  --output-on-failure
