name: runtime cmake version check
on: [push, pull_request]
jobs:
    minimum-version-check:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                cmake: [3.12, 3.13]
                        
                compiler:
                    - cc: gcc-10
                      cxx: g++-10
                    - cc: clang-10
                      cxx: clang++-10          
        env:
            cmake: ${{ matrix.cmake }} 
            CC: ${{ matrix.compiler.cc }}
            CXX: ${{ matrix.compiler.cxx }} 
           
        steps:  
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Check dependencies
              run: |
                  sudo apt-get update 
                  sudo apt-get install -y curl wget git ninja-build g++ libboost-all-dev libssl-dev build-essential
                  
            - name: Install different versions of cmake
              run: |
                  wget http://www.cmake.org/files/v${{ matrix.cmake }}/cmake-${{ matrix.cmake }}.0-Linux-x86_64.tar.gz
                  tar -zxvf ${{ matrix.cmake }}.0-Linux-x86_64.tar.gz
                  cd cmake-${{ matrix.cmake }}.0-Linux-x86_64/
                  export PATH=$PATH:$(pwd)/bin
                  cmake --version
              
            - name: CMake configure
              run: |
                  export BOOST_ROOT="$(pwd)/boost_root"
                  mkdir build
                  cmake -S ./ -B ./build
                  
            - name: CMake build
              run: |
                  cmake --build ./build
              
            - name: Run tests
              run: |
                 cmake --build ./build --target SMCE_Tests
                 ctest
